-- Admin Seed SQL (generated by scripts/seed-admin.mjs)
-- Admin: admin@pg.com / admin123
-- Run: npx wrangler d1 execute rent --local --file=./seed.sql

-- Create admin user
INSERT OR IGNORE INTO users (name, email, phone, password_hash, role, is_active, created_at)
VALUES ('Admin', 'admin@pg.com', '9999999999', '91f149297279563e3921509bd2cc61ae:96ed93d812441c32664f7674480d791028af4f387a45bf2bc6cccb77fd914b2f', 'admin', 1, datetime('now'));

-- Create sample rooms with beds
INSERT OR IGNORE INTO rooms (name, description, created_at) VALUES
  ('Room 101', 'Ground floor, AC room', datetime('now')),
  ('Room 202', 'Second floor, fan room', datetime('now'));

INSERT OR IGNORE INTO beds (room_id, name, status, monthly_rent, created_at) VALUES
  (1, 'Bed A', 'available', 5000, datetime('now')),
  (1, 'Bed B', 'available', 5000, datetime('now')),
  (1, 'Bed C', 'available', 5500, datetime('now')),
  (2, 'Bed A', 'available', 4000, datetime('now')),
  (2, 'Bed B', 'available', 4000, datetime('now'));

-- Default settings
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES
  ('rent_due_start_day', '1',    datetime('now')),
  ('rent_due_end_day',   '5',    datetime('now')),
  ('late_fee_amount',    '100',  datetime('now')),
  ('deposit_amount',     '5000', datetime('now'));
