/**
 * Admin Seed Script
 *
 * Run this to create an admin user + sample rooms + default settings.
 * Usage:
 *   cd server
 *   node scripts/seed-admin.mjs
 *
 * Then apply the generated SQL:
 *   npx wrangler d1 execute rent --local --file=./seed.sql
 */

const ITERATIONS = 100_000;
const KEY_LENGTH = 32;

async function hashPassword(password) {
  const encoder = new TextEncoder();
  const saltBytes = crypto.getRandomValues(new Uint8Array(16));
  const salt = Array.from(saltBytes).map(b => b.toString(16).padStart(2, '0')).join('');

  const keyMaterial = await crypto.subtle.importKey(
    'raw',
    encoder.encode(password),
    'PBKDF2',
    false,
    ['deriveBits']
  );

  const hashBuffer = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', salt: saltBytes, iterations: ITERATIONS, hash: 'SHA-256' },
    keyMaterial,
    KEY_LENGTH * 8
  );

  const hash = Array.from(new Uint8Array(hashBuffer)).map(b => b.toString(16).padStart(2, '0')).join('');
  return `${salt}:${hash}`;
}

async function main() {
  const adminEmail = process.argv[2] || 'admin@pg.com';
  const adminPassword = process.argv[3] || 'admin123';

  console.log(`\nGenerating admin seed...`);
  console.log(`  Email: ${adminEmail}`);
  console.log(`  Password: ${adminPassword}`);

  const passwordHash = await hashPassword(adminPassword);

  const sql = `-- Admin Seed SQL (generated by scripts/seed-admin.mjs)
-- Admin: ${adminEmail} / ${adminPassword}
-- Run: npx wrangler d1 execute rent --local --file=./seed.sql

-- Create admin user
INSERT OR IGNORE INTO users (name, email, phone, password_hash, role, is_active, created_at)
VALUES ('Admin', '${adminEmail}', '9999999999', '${passwordHash}', 'admin', 1, datetime('now'));

-- Create sample rooms with beds
INSERT OR IGNORE INTO rooms (name, description, created_at) VALUES
  ('Room 101', 'Ground floor, AC room', datetime('now')),
  ('Room 202', 'Second floor, fan room', datetime('now'));

INSERT OR IGNORE INTO beds (room_id, name, status, monthly_rent, created_at) VALUES
  (1, 'Bed A', 'available', 5000, datetime('now')),
  (1, 'Bed B', 'available', 5000, datetime('now')),
  (1, 'Bed C', 'available', 5500, datetime('now')),
  (2, 'Bed A', 'available', 4000, datetime('now')),
  (2, 'Bed B', 'available', 4000, datetime('now'));

-- Default settings
INSERT OR IGNORE INTO settings (key, value, updated_at) VALUES
  ('rent_due_start_day', '1',    datetime('now')),
  ('rent_due_end_day',   '5',    datetime('now')),
  ('late_fee_amount',    '100',  datetime('now')),
  ('deposit_amount',     '5000', datetime('now'));
`;

  const fs = await import('fs');
  fs.writeFileSync('seed.sql', sql);
  console.log(`\n✓ seed.sql written!`);
  console.log(`\nNow run:\n  npx wrangler d1 execute rent --local --file=./seed.sql\n`);
}

main().catch(console.error);
